version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: always
    links:
      - db:db
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .ideerss.env #This should be in your root project directory along side the Dockerfile and docker-compose file